export enum VinAddStatus {
  NOT_USED = 'NOT_USED',
  PENDING = 'PENDING',
  COMMITTED_LOCKED = 'COMMITTED_LOCKED',
  FAILED_INELIGIBLE = 'FAILED_INELIGIBLE',
  FAILED_DEPENDENCY = 'FAILED_DEPENDENCY',
  FAILED_VALIDATION = 'FAILED_VALIDATION',
  CANCELLED = 'CANCELLED',
}
