FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
ENV DD_TRACE_ENABLED=true
ENV DD_SERVICE=vin-portal-api
EXPOSE 3000
CMD ["node", "dist/main"]
