export const ErrorCodes = {
  // Auth
  AUTH_NO_MATCH: 'AUTH_NO_MATCH',
  AUTH_OTP_REQUIRED: 'AUTH_OTP_REQUIRED',
  AUTH_EXPIRED: 'AUTH_EXPIRED',
  AUTH_INVALID: 'AUTH_INVALID',
  // Rate limiting
  RATE_LIMITED: 'RATE_LIMITED',
  // OTP
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_LOCKED_OUT: 'OTP_LOCKED_OUT',
  // VIN
  VIN_INVALID_FORMAT: 'VIN_INVALID_FORMAT',
  VIN_DECODE_FAILED: 'VIN_DECODE_FAILED',
  VIN_INELIGIBLE: 'VIN_INELIGIBLE',
  VIN_ALREADY_COMMITTED: 'VIN_ALREADY_COMMITTED',
  // Contract
  CONTRACT_LOCKED: 'CONTRACT_LOCKED',
  CONTRACT_NOT_FOUND: 'CONTRACT_NOT_FOUND',
  // System
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
