export const EventTypes = {
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAILURE: 'AUTH_FAILURE',
  AUTH_OTP_TRIGGERED: 'AUTH_OTP_TRIGGERED',
  OTP_SENT: 'OTP_SENT',
  OTP_VERIFIED: 'OTP_VERIFIED',
  OTP_FAILED: 'OTP_FAILED',
  OTP_LOCKED_OUT: 'OTP_LOCKED_OUT',
  VIN_DECODED: 'VIN_DECODED',
  VIN_ELIGIBILITY_CHECKED: 'VIN_ELIGIBILITY_CHECKED',
  VIN_COMMIT_REQUESTED: 'VIN_COMMIT_REQUESTED',
  VIN_COMMIT_SUCCESS: 'VIN_COMMIT_SUCCESS',
  VIN_COMMIT_PENDING: 'VIN_COMMIT_PENDING',
  VIN_COMMIT_FAILED: 'VIN_COMMIT_FAILED',
  WORKER_RETRY: 'WORKER_RETRY',
  WORKER_FINAL_FAILURE: 'WORKER_FINAL_FAILURE',
  DEPENDENCY_RETRY: 'DEPENDENCY_RETRY',
  ADMIN_VIEW: 'ADMIN_VIEW',
  ADMIN_NOTE: 'ADMIN_NOTE',
} as const;

export type EventType = (typeof EventTypes)[keyof typeof EventTypes];
