export const CONTRACT_VERIFICATION_ADAPTER = Symbol('CONTRACT_VERIFICATION_ADAPTER');
export const VIN_DECODE_ADAPTER = Symbol('VIN_DECODE_ADAPTER');
export const ELIGIBILITY_ADAPTER = Symbol('ELIGIBILITY_ADAPTER');
export const ASSOCIATION_ADAPTER = Symbol('ASSOCIATION_ADAPTER');
